# SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
# CASE 
#     WHEN FREEZER_YN IS NULL THEN 'N'
#     ELSE FREEZER_YN
# END AS FREEZER_YN
# FROM FOOD_WAREHOUSE
# WHERE ADDRESS LIKE '경기도%'
# ORDER BY WAREHOUSE_ID;

#CASE WHEN (조건식1) THEN (조건식1 반환값)
#     WHEN (조건식2) THEN (조건식2 반환값)
#     ELSE (조건식1,2가 충족안될 때 반환값)
#END

# IF(조건식, 참일 때 값, 거짓일 때 값)
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IF(FREEZER_YN IS NULL,'N',FREEZER_YN) AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID;
